default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5
  username: dave
  password: fay586tb

development:
  <<: *default
  database: 1rlc-lad_development

test:
  <<: *default
  database: 1rlc-lad_test

production:
  <<: *default
  database: 1rlc-lad_production
